plugins {
    id 'com.android.application'
}

android {
    namespace 'com.billarazteca.marcador'
    compileSdk 35

    defaultConfig {
        applicationId 'com.billarazteca.marcador.v9'
        minSdk 26
        targetSdk 35
        versionCode 9
        versionName '1.2.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
